rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'PHP 7.4 Unit Test'
    - 'PHP 7.4 --prefer-lowest Unit Test'
    - 'PHP 8.0 Unit Test'
    - 'PHP 8.1 Unit Test'
    - 'PHP 8.2 Unit Test'
    - 'PHP 8.3 Unit Test'
    - 'PHP 8.3 --prefer-lowest Unit Test'
    - 'PHP Style Check'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-php-admins
    permission: admin
  - team: yoshi-php
    permission: push
